### PR TITLE
Return intended reference instead of retrieving the value

### PR DESCRIPTION
**Pull request by homestar9**
See  https://github.com/coldbox-modules/swagger-sdk/issues/16

### CODE REVIEW

**Comment by jclausen** [comment]
When I saw your PR and plugged it in to my test suite, I thought it was going to resolve the issue ( I have been working on it ) but it's not a workable solution, once the document is fully normalized all the way down. It would only work with a top-level document being parsed.

Take this example,  using the OpenAPI Petstore Schema for v3. If below is my top level document and the `$ref` for `paths` contains a back-reference to the `$ref` of the parent inside it's own schema, the back-reference goes missing when the document is normalized.  I am going to dig in to this a bit further.  I may have to add conditionals or move back references up to the root if they are encountered.  

```
{
	"openapi": "3.0.2",
	"info": {
		"title": "Swagger Petstore - OpenAPI 3.0",
		"description": "This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about\nSwagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!\nYou can now help us improve the API whether it's by making changes to the definition itself or to the code.\nThat way, with time, we can improve the API in general, and expose some of the new features in OAS3.\n\nSome useful links:\n- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)\n- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)",
		"termsOfService": "http://swagger.io/terms/",
		"contact": {
			"email": "apiteam@swagger.io"
		},
		"license": {
			"name": "Apache 2.0",
			"url": "http://www.apache.org/licenses/LICENSE-2.0.html"
		},
		"version": "1.0.17"
	},
	"externalDocs": {
		"description": "Find out more about Swagger",
		"url": "http://swagger.io"
	},
	"servers": [
		{
			"url": "/api/v3"
		}
	],
	"tags": [
		{
			"name": "pet",
			"description": "Everything about your Pets",
			"externalDocs": {
				"description": "Find out more",
				"url": "http://swagger.io"
			}
		},
		{
			"name": "store",
			"description": "Access to Petstore orders",
			"externalDocs": {
				"description": "Find out more about our store",
				"url": "http://swagger.io"
			}
		},
		{
			"name": "user",
			"description": "Operations about user"
		}
	],
	"paths": {
		"$ref": "paths/pets.json#/paths"
	}
}
```

**Comment by homestar9** [comment]
I want to make sure I understand.  The above example is your `cbswagger` config?  

Does it help by adding `getNormalizedDocument()` in the `fetchDocumentreference()` method?
My current fork of the repo does this: https://github.com/homestar9/swagger-sdk/commit/42e5ea6393264ff4c808fc82684abe70634c96ea
The above approach normalizes each document reference individually.

**Comment by jclausen** [comment]
I have pushed commits to the `development` branch which resolve the `$ref` inheritance handling.   It's easier to illustrate if you look at the updated test schema files: https://github.com/coldbox-modules/swagger-sdk/blob/development/test-harness/tests/resources/petstore/petstore.json

What was happening with this PR was that deep `$ref` keys weren't being expanded.  This was because the reference to the root document was lost on the first expansion.  I handled this by maintaining a reference to the rootDocument that could be used for inheritance lookups. 

I would like your work to be represented in this repo.  If you could pull in the lastest `development` branch to your branch above for `allOf` handling and pull request those code changes, I will use that as the foundation for handling that inheritance functionality.  Then I can add tests and take care of a few more issues before I release v3 of the SDK.

**Comment by homestar9** [comment]
https://github.com/coldbox-modules/swagger-sdk/pull/18  (see my notes about the tests -- I think it's going to take some creativity here)
Edit: I forgot to pull `development` first.  I'll create a new PR.

**Pull request closed without merging**
